### ISSUE TITLE
セッション管理を行わない

### ISSUE THREAD

**Issue by syuilo** [syuilo/misskey-web#10]

**Comment by syuilo** [comment]
その場合Redisへの依存もなくなりすっきりする
あとHTMLが完全に静的になる

**Comment by Petitsurume** [comment]
その場合どうやってユーザーを識別するの

**Comment by syuilo** [comment]
@Petitsurume CookieにWebシークレット(APIキーのようなもの)を保存しておく
APIへリクエストする際はそのキーを付けてリクエスト

**Comment by Petitsurume** [comment]
@syuilo Twitterでいうアクセストークンのようなもの？

**Comment by syuilo** [comment]
@Petitsurume そり

**Comment by Petitsurume** [comment]
@syuilo わかりすぎてわかになった！

**Comment by syuilo** [comment]
セキュリティ的に大丈夫だよね？
他サイトから他サイトのCookie見れたりしないし

**Comment by Petitsurume** [comment]
それを無効化できる機能はあったほうが安心

**Comment by Petitsurume** [comment]
wordpressのこり
![image](https://cloud.githubusercontent.com/assets/6533808/18024808/94bdb898-6c4e-11e6-8d53-e9fb9f20ea95.png)

**Comment by syuilo** [comment]
ふぅむ
つまりアクセストークン再発行みたいな感じ？

**Comment by Petitsurume** [comment]
現在アカウントに紐付けられているアクセストークンをすべて無効化するみたいな
