### ISSUE TITLE
Proxy機能において許可したドメインのみアクセス許可とする

### ISSUE THREAD

**Issue by otofune** [syuilo/misskey-web#18]
- リクエストヘッダーを表示するプログラムを書いてそこにアクセスさせると生IPが露見してしまう  
CloudFlareの利用による生IP隠匿のメリットを潰してしまう
- 大きなファイルを経由で落とされた場合回線/リソースが食い潰される可能性がある

**Comment by syuilo** [comment]
どんなドメインが来るかあらかじめわからないので別ドメインにするようにします
