### ISSUE TITLE
リポジトリへのリンクがわかりにくい

### ISSUE THREAD

**Issue by takeyari** [syuilo/misskey-web#53]
リポジトリへのリンクが文章と同色のためどこを押せばいいのかわかりにくいです
「こちら」の文字を変えるか開発者募集の枠全体をボタンのようにしたほうがいいと思われます
https://gyazo.com/72bd1b302a433eeab0aa895dce32ec55

**Comment by syuilo** [comment]
賑やかしのために置いているだけなので、前者だと目立ちすぎるのでやるとしたら後者
