### ISSUE TITLE
スクロールむっちゃ重い

### ISSUE THREAD

**Issue by Petitsurume** [syuilo/misskey-web#54]
スクロールむっちゃ重い
ブラウザはChrome53、OSはLinux(Arch)

**Comment by sirotama** [comment]
これほんま重いから早く治して

**Comment by atnanasi** [comment]
スクロール中は範囲選択とかも効かなくなっててるのでつらい

**Comment by otofune** [comment]
Firefox Dev 51.0.a2、OS Windows 7でも起きる

**Comment by syuilo** [comment]
原因解りました

**Comment by Petitsurume** [comment]
何

**Comment by syuilo** [comment]
おそらくスタイルを弄った影響で、一番下までスクロールが到達してないのに一番下までスクロールされたと判断され、スクロールするごとにタイムラインがread moreされることが原因

**Comment by Petitsurume** [comment]
なるほどね
