### ISSUE TITLE
長いURLがはみ出る

### ISSUE THREAD

**Issue by Petitsurume** [syuilo/misskey-web#61]
iOS9.3.5 Safari
http://imgur.com/Cw3S1NH

**Comment by Petitsurume** [comment]
なおってない
![image](https://cloud.githubusercontent.com/assets/6533808/20008240/2a4fd07e-a2e3-11e6-91bb-af0d1f8fc65d.png)

**Comment by syuilo** [comment]
まだデプロイしていません

**Comment by Petitsurume** [comment]
なるほどね？
